import Head from 'next/head'
import Header from '../components/Header'
import {collection, query, orderBy, onSnapshot} from "firebase/firestore"
import { db } from '../firebase'
import { useState, useEffect } from 'react'

import Album from '../components/Album'


export default function Home() {
  const [albums, setAlbums] = useState([])

  useEffect(() => {
    const q = query(collection(db, 'albums'), orderBy('created', 'desc'))
    onSnapshot(q, (querySnapshot) => {
      setAlbums(querySnapshot.docs.map(doc => ({
        id: doc.id,
        data: doc.data()
      })))
    })
  }, [])
  return (
    <div className="bg-pink-100 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className='mt-8 mx-auto w-[90%] grid grid-cols-1 md:grid-cols-3 justify-between gap-10'>
        {
          albums.map(album => (
            <Album key={album.id} liked={album.data.liked} cover={album.data.cover} title={album.data.title} id={album.id} />
          ))
        }
      </div>
    </div>
  )
}
